name: CI/CD React App to AKS

on:
  push:
    branches:
      - main

env:
  IMAGE: ghaitho20/react-frontend
  TAG: latest

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: PCD-frontend         
          cluster-name: AKS-frontend-pcd-app
    

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/react-deployment.yaml
          kubectl apply -f k8s/react-service.yaml
